export enum SessionError {
  INVALID_STRATEGY = 'INVALID_STRATEGY',
  INVALID_ROUND_DATA = 'INVALID_ROUND_DATA',
  ENGINE_ERROR = 'ENGINE_ERROR',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  SESSION_TERMINAL = 'SESSION_TERMINAL',
  INVALID_TRANSITION = 'INVALID_TRANSITION',
  TIMEOUT = 'TIMEOUT',
}
