// ─── Smart Contracts Package ─────────────────────────────────
// Post-MVP: Solidity smart contracts compiled with Foundry.
// This package will export ABIs, deployed addresses, and
// TypeScript bindings generated by viem/wagmi.

// TODO(post-mvp): Initialize Foundry project (forge init)
// TODO(post-mvp): Implement HaggleEscrow.sol on Base L2
// TODO(post-mvp): Export contract ABIs and addresses
// TODO(post-mvp): Integrate x402 USDC payment protocol

export interface ContractAddresses {
  settlementRouter: `0x${string}` | null;
  disputeRegistry: `0x${string}` | null;
}

export const CONTRACT_ADDRESSES: ContractAddresses = {
  settlementRouter: null,
  disputeRegistry: null,
};

export const HAGGLE_SETTLEMENT_ROUTER_ABI = [
  {
    type: "function",
    name: "executeSettlement",
    stateMutability: "nonpayable",
    inputs: [
      { name: "orderId", type: "bytes32" },
      { name: "paymentIntentId", type: "bytes32" },
      { name: "buyer", type: "address" },
      { name: "seller", type: "address" },
      { name: "sellerWallet", type: "address" },
      { name: "feeWallet", type: "address" },
      { name: "asset", type: "address" },
      { name: "grossAmount", type: "uint256" },
      { name: "sellerAmount", type: "uint256" },
      { name: "feeAmount", type: "uint256" },
      { name: "approvalSnapshotHash", type: "bytes32" },
      { name: "reservationId", type: "bytes32" },
    ],
    outputs: [{ name: "executionId", type: "bytes32" }],
  },
  {
    type: "event",
    name: "SettlementExecuted",
    inputs: [
      { indexed: true, name: "executionId", type: "bytes32" },
      { indexed: true, name: "orderId", type: "bytes32" },
      { indexed: false, name: "paymentIntentId", type: "bytes32" },
      { indexed: false, name: "sellerWallet", type: "address" },
      { indexed: false, name: "feeWallet", type: "address" },
      { indexed: false, name: "grossAmount", type: "uint256" },
      { indexed: false, name: "sellerAmount", type: "uint256" },
      { indexed: false, name: "feeAmount", type: "uint256" },
    ],
    anonymous: false,
  },
] as const;

export const HAGGLE_DISPUTE_REGISTRY_ABI = [
  {
    type: "function",
    name: "anchorDispute",
    stateMutability: "nonpayable",
    inputs: [
      { name: "orderId", type: "bytes32" },
      { name: "disputeCaseId", type: "bytes32" },
      { name: "evidenceRootHash", type: "bytes32" },
      { name: "resolutionHash", type: "bytes32" },
    ],
    outputs: [{ name: "anchorId", type: "bytes32" }],
  },
  {
    type: "event",
    name: "DisputeAnchored",
    inputs: [
      { indexed: true, name: "anchorId", type: "bytes32" },
      { indexed: true, name: "orderId", type: "bytes32" },
      { indexed: false, name: "disputeCaseId", type: "bytes32" },
      { indexed: false, name: "evidenceRootHash", type: "bytes32" },
      { indexed: false, name: "resolutionHash", type: "bytes32" },
    ],
    anonymous: false,
  },
] as const;
