import type { Locale } from "@/lib/i18n";

const en = {
  title: "Secure checkout",
  subtitle: "Review the agreed terms, choose card or USDC, then connect your wallet.",
  back: "Back to negotiation",
  accepted: "Deal accepted",
  negotiatedPrice: "Negotiated price",
  fundsNote: "Funds follow the accepted agreement and remain subject to release rules.",
  buyerNote: "Payment preparation is restricted to the buyer on this negotiation.",
  language: "Display language",
  loadingPayment: "Loading payment options...",
  paymentTitle: "Secure payment",
  methodHeading: "Choose a payment method",
  cardTitle: "Pay with card",
  cardDescription:
    "Stripe converts the card payment to USDC. The complete fee is shown before authorization.",
  directTitle: (asset: string, amount: string) => `${asset} Direct (${amount})`,
  directDescription: (network: string) =>
    `Pay from a ${network} wallet. Haggle shows the settlement and seller fee before authorization.`,
  assetNote: (asset: string, network: string) => `Settlement asset: ${asset} on ${network}`,
  includesFee: (amount: string) => `includes ${amount} buyer fee`,
  progressSteps: ["Method", "Wallet", "Quote", "Pay", "Complete"],
  backToOptions: "Back to payment options",
  backToWallet: "Back to wallet",
  backToQuote: "Back to quote",
  testnetTitle: "Base Sepolia testnet",
  testnetNote: (asset: string) =>
    `This checkout accepts test ETH and ${asset} only. These assets have no monetary value.`,
  fulfillmentTitle: "Choose a fulfillment test",
  fulfillmentNote: "This choice is locked when payment preparation starts.",
  integrationTitle: "Integration test",
  integrationDescription:
    "Use EasyPost test rates and labels. The team can advance carrier states without moving a parcel.",
  physicalTitle: "Physical shipping rehearsal",
  physicalDescription: (amount: string) =>
    `Use real addresses, a paid EasyPost label, and actual carrier scans. Haggle pays up to $${amount} in staging postage.`,
  shippingSetupTitle: "Physical shipping setup is incomplete",
  shippingSetupNote: "Shipping readiness could not be verified.",
  postageTitle: "Real postage, test settlement",
  postageNote: (asset: string) =>
    `EasyPost charges Haggle's staging payment method in USD. The order settlement still uses ${asset}, which has no monetary value and does not reimburse that postage.`,
  chooseShippingHint: "Choose a fulfillment test above to enable both payment options.",
  savedTitle: "Payment choices saved",
  savedNote:
    "Shipping mode and payment method are locked after payment preparation. You can review them here, then continue without reconnecting your wallet.",
  continuePayment: "Continue payment",
  stripeActive: "Complete the payment in Stripe.",
  stripeLoading: "Setting up card payment...",
  connectCard: "Connect the wallet that should receive USDC after your card payment.",
  connectDirect: "Connect your wallet to pay with USDC.",
  connectWallet: "Connect wallet",
  walletsHint: "Choose MetaMask, Coinbase Wallet, or another supported wallet.",
  connected: "Wallet connected",
  changeWallet: "Change",
  switchTitle: (network: string) => `Switch to ${network}`,
  switchNote: "This checkout blocks transactions from every other network.",
  switchNetwork: "Switch network",
  preparing: "Preparing...",
  continuePrepared: "Continue prepared payment",
  continue: "Continue",
  yourAddress: "Your address",
  ethBalance: "ETH balance",
  rail: "Payment method",
  buyerPays: "Buyer pays",
  sellerReceives: "Seller receives",
  cardRail: "Card via Stripe",
  directRail: (asset: string) => `${asset} Direct`,
  cardFees: "Buyer pays the Stripe onramp fee. Haggle fee is deducted from seller proceeds.",
  directFees: "No buyer fee. Haggle fee is deducted from seller proceeds.",
  fundedTitle: "Card on-ramp funded — finish settlement",
  fundedNote: (asset: string) =>
    `Stripe funded your wallet. Next, quote and fund the conditional settlement contract with ${asset} (staging uses base-sepolia test assets; Onramp itself targets Base).`,
  waitingQuote: "Waiting for on-ramp webhook / quoting...",
  loading: "Loading...",
  getQuote: (asset: string) => `Get ${asset} Quote`,
  continueSettlement: (asset: string) => `Continue to ${asset} settlement`,
  confirmDeposit: (amount: string) =>
    `Confirm once in your wallet to approve and securely deposit ${amount}. The seller is paid only after the release conditions are met.`,
  settlementAmount: "Settlement amount",
  buyerFee: "Buyer fee",
  sellerFee: "Seller fee",
  atomicNote: "Approval and deposit run together. If either action fails, neither is applied.",
  confirming: "Confirming payment...",
  pay: (amount: string) => `Pay ${amount} securely`,
  confirmedTitle: "Funding confirmed",
  submittedTitle: "Payment submitted",
  confirmedDescription: (amount: string) =>
    `Your ${amount} funding transaction is confirmed. The funds remain protected by the release and dispute rules.`,
  submittedDescription: (amount: string) =>
    `Your payment of ${amount} was submitted. If you used card on-ramp, confirm conditional settlement funding still completed.`,
  viewOrder: "View order",
  errorTitle: "Payment could not continue",
  retry: "Try Again",
  connectRequired: "Connect a wallet before continuing.",
  shippingRequired: "Choose a fulfillment test before continuing.",
  intentMissing: "The payment intent or order was not returned.",
  networkRequired: (network: string) => `Switch your wallet to ${network} before continuing.`,
  quoteMissing: (asset: string) => `${asset} quote did not include a confirmed settlement amount.`,
  onrampWalletRequired: "Connect a wallet before starting card onramp.",
  requestRequired: "A verified conditional settlement request is required before funding.",
  atomicFailed: "The wallet did not complete the payment as one atomic transaction.",
  transactionMissing: "The wallet did not return the confirmed payment transaction hash.",
  atomicUnsupported:
    "This wallet cannot combine approval and payment into one confirmation. Use a wallet with atomic batch support.",
};

const ko: typeof en = {
  title: "안전한 결제",
  subtitle: "합의 내용을 확인하고 카드 또는 USDC를 선택한 뒤 지갑을 연결합니다.",
  back: "협상으로 돌아가기",
  accepted: "협상 완료",
  negotiatedPrice: "협상한 가격",
  fundsNote: "자금은 합의한 조건에 따라 처리되며 지급 조건이 적용됩니다.",
  buyerNote: "이 협상의 구매자만 결제를 준비할 수 있습니다.",
  language: "표시 언어",
  loadingPayment: "결제 수단을 불러오는 중...",
  paymentTitle: "안전한 결제",
  methodHeading: "결제 수단 선택",
  cardTitle: "카드로 결제",
  cardDescription:
    "Stripe가 카드 결제액을 USDC로 전환합니다. 승인 전에 전체 수수료를 확인할 수 있습니다.",
  directTitle: (asset, amount) => `${asset} 직접 결제 (${amount})`,
  directDescription: (network) =>
    `${network} 지갑에서 결제합니다. 승인 전에 정산 금액과 판매자 수수료를 확인할 수 있습니다.`,
  assetNote: (asset, network) => `정산 자산: ${network}의 ${asset}`,
  includesFee: (amount) => `구매자 수수료 ${amount} 포함`,
  progressSteps: ["수단", "지갑", "견적", "결제", "완료"],
  backToOptions: "결제 수단으로 돌아가기",
  backToWallet: "지갑으로 돌아가기",
  backToQuote: "견적으로 돌아가기",
  testnetTitle: "Base Sepolia 테스트넷",
  testnetNote: (asset) =>
    `이 결제는 테스트 ETH와 ${asset}만 사용합니다. 이 자산에는 금전적 가치가 없습니다.`,
  fulfillmentTitle: "배송 테스트 선택",
  fulfillmentNote: "결제 준비를 시작하면 이 선택이 고정됩니다.",
  integrationTitle: "연동 테스트",
  integrationDescription:
    "EasyPost 테스트 요금과 운송장을 사용합니다. 실제 소포를 이동하지 않고 배송 상태를 진행할 수 있습니다.",
  physicalTitle: "실배송 리허설",
  physicalDescription: (amount) =>
    `실제 주소, 유료 EasyPost 운송장과 배송 스캔을 사용합니다. Haggle이 스테이징 배송비를 최대 $${amount} 부담합니다.`,
  shippingSetupTitle: "실배송 설정이 완료되지 않았습니다",
  shippingSetupNote: "배송 준비 상태를 확인하지 못했습니다.",
  postageTitle: "실제 배송비, 테스트 정산",
  postageNote: (asset) =>
    `EasyPost는 Haggle의 스테이징 결제 수단에 USD로 청구합니다. 주문 정산에는 금전적 가치가 없는 ${asset}를 사용하며 배송비를 상환하지 않습니다.`,
  chooseShippingHint: "위에서 배송 테스트를 선택하면 두 결제 수단을 선택할 수 있습니다.",
  savedTitle: "결제 선택 저장됨",
  savedNote:
    "결제 준비 후 배송 방식과 결제 수단이 고정됩니다. 여기에서 확인하고 지갑을 다시 연결하지 않고 계속할 수 있습니다.",
  continuePayment: "결제 계속하기",
  stripeActive: "Stripe에서 결제를 완료하세요.",
  stripeLoading: "카드 결제를 준비하는 중...",
  connectCard: "카드 결제 후 USDC를 받을 지갑을 연결하세요.",
  connectDirect: "USDC로 결제할 지갑을 연결하세요.",
  connectWallet: "지갑 연결",
  walletsHint: "MetaMask, Coinbase Wallet 또는 지원되는 다른 지갑을 선택하세요.",
  connected: "지갑 연결됨",
  changeWallet: "변경",
  switchTitle: (network) => `${network}로 전환`,
  switchNote: "다른 네트워크에서는 이 결제를 진행할 수 없습니다.",
  switchNetwork: "네트워크 전환",
  preparing: "준비 중...",
  continuePrepared: "준비된 결제 계속하기",
  continue: "계속",
  yourAddress: "내 지갑 주소",
  ethBalance: "ETH 잔액",
  rail: "결제 수단",
  buyerPays: "구매자 결제액",
  sellerReceives: "판매자 수령액",
  cardRail: "Stripe 카드 결제",
  directRail: (asset) => `${asset} 직접 결제`,
  cardFees:
    "구매자가 Stripe 온램프 수수료를 부담합니다. Haggle 수수료는 판매자 수령액에서 차감됩니다.",
  directFees: "구매자 수수료가 없습니다. Haggle 수수료는 판매자 수령액에서 차감됩니다.",
  fundedTitle: "카드 온램프 완료 — 정산을 마무리하세요",
  fundedNote: (asset) =>
    `Stripe가 지갑에 자금을 넣었습니다. 다음으로 ${asset} 견적을 확인하고 조건부 정산에 입금하세요. 스테이징 정산은 base-sepolia 테스트 자산, 온램프는 Base를 사용합니다.`,
  waitingQuote: "온램프 확인과 견적을 기다리는 중...",
  loading: "불러오는 중...",
  getQuote: (asset) => `${asset} 견적 확인`,
  continueSettlement: (asset) => `${asset} 정산 계속하기`,
  confirmDeposit: (amount) =>
    `지갑에서 한 번 확인하여 ${amount}의 승인과 안전한 예치를 진행하세요. 판매자 지급은 지급 조건을 충족한 뒤에 이루어집니다.`,
  settlementAmount: "정산 금액",
  buyerFee: "구매자 수수료",
  sellerFee: "판매자 수수료",
  atomicNote: "승인과 예치는 함께 실행됩니다. 하나라도 실패하면 둘 다 적용되지 않습니다.",
  confirming: "결제 확인 중...",
  pay: (amount) => `${amount} 안전하게 결제`,
  confirmedTitle: "입금 확인됨",
  submittedTitle: "결제 전송됨",
  confirmedDescription: (amount) =>
    `${amount} 입금 거래가 확인되었습니다. 자금에는 지급과 분쟁 규칙이 계속 적용됩니다.`,
  submittedDescription: (amount) =>
    `${amount} 결제를 전송했습니다. 카드 온램프를 사용했다면 조건부 정산 입금도 완료되었는지 확인하세요.`,
  viewOrder: "주문 보기",
  errorTitle: "결제를 계속할 수 없습니다",
  retry: "다시 시도",
  connectRequired: "계속하려면 지갑을 연결하세요.",
  shippingRequired: "계속하려면 배송 테스트를 선택하세요.",
  intentMissing: "결제 정보 또는 주문이 반환되지 않았습니다.",
  networkRequired: (network) => `계속하려면 지갑을 ${network}로 전환하세요.`,
  quoteMissing: (asset) => `${asset} 견적에 확인된 정산 금액이 없습니다.`,
  onrampWalletRequired: "카드 온램프를 시작하려면 지갑을 연결하세요.",
  requestRequired: "입금 전에 검증된 조건부 정산 요청이 필요합니다.",
  atomicFailed: "지갑이 결제를 하나의 원자적 거래로 완료하지 못했습니다.",
  transactionMissing: "지갑이 확인된 결제 거래 해시를 반환하지 않았습니다.",
  atomicUnsupported:
    "이 지갑은 승인과 결제를 한 번의 확인으로 처리할 수 없습니다. 원자적 일괄 처리를 지원하는 지갑을 사용하세요.",
};

export function checkoutCopy(locale: Locale) {
  return locale === "ko" ? ko : en;
}
