import type { CategoryTerm } from '../types.js';

/** Phase 0 Electronics 표준 Term — iPhone Pro 카테고리 */
export const ELECTRONICS_TERMS: CategoryTerm[] = [
  {
    id: 'battery_health',
    parent_category: 'CONDITION',
    display_name: '배터리 잔여 수명',
    value_type: 'number',
    value_range: { min: 0, max: 100 },
    unit: '%',
    typical_impact: '80% 미만 시 $50-100 감가',
    evaluate_hint: 'Battery below 80% significantly reduces resale value. Each 10% below 80 = ~$30 deduction.',
  },
  {
    id: 'carrier_lock',
    parent_category: 'VERIFICATION',
    display_name: '통신사 잠금',
    value_type: 'enum',
    value_range: ['unlocked', 'locked'],
    typical_impact: '잠금 해제 시 $30-50 프리미엄',
    evaluate_hint: 'Unlocked devices command $30-50 premium over carrier-locked equivalents.',
  },
  {
    id: 'screen_condition',
    parent_category: 'CONDITION',
    display_name: '화면 상태',
    value_type: 'enum',
    value_range: ['flawless', 'minor_scratches', 'cracks', 'replaced'],
    typical_impact: '크랙 시 $80-150 감가, 교체 이력 시 $30-50 감가',
    evaluate_hint: 'Cracked screen: -$80~150. Replaced screen (non-OEM): -$30~50. Minor scratches: minimal impact.',
  },
  {
    id: 'storage_capacity',
    parent_category: 'CONDITION',
    display_name: '저장 용량',
    value_type: 'enum',
    value_range: ['128GB', '256GB', '512GB', '1TB'],
    typical_impact: '용량 단계당 $50-80 차이',
    evaluate_hint: 'Each storage tier adds ~$50-80 to value. 128GB is baseline.',
  },
  {
    id: 'original_accessories',
    parent_category: 'CONDITION',
    display_name: '정품 액세서리 포함',
    value_type: 'boolean',
    typical_impact: '정품 박스+충전기 포함 시 $20-30 프리미엄',
    evaluate_hint: 'Original box and accessories add $20-30 to perceived value.',
  },
  {
    id: 'find_my_status',
    parent_category: 'VERIFICATION',
    display_name: 'Find My 비활성화',
    value_type: 'boolean',
    typical_impact: '미비활성화 시 거래 불가',
    evaluate_hint: 'Find My must be disabled before sale. This is a deal-breaker if not confirmed.',
  },
  {
    id: 'shipping_method',
    parent_category: 'LOGISTICS',
    display_name: '배송 방법',
    value_type: 'enum',
    value_range: ['local_pickup', 'standard_shipping', 'express_shipping', 'insured_shipping'],
    typical_impact: '보험 배송 $15-25 추가, 직거래 시 무료',
    evaluate_hint: 'Insured shipping adds $15-25 but reduces risk. Local pickup saves cost for both parties.',
  },
  {
    id: 'shipping_cost_split',
    parent_category: 'FINANCIAL',
    display_name: '배송비 부담',
    value_type: 'enum',
    value_range: ['buyer_pays', 'seller_pays', 'split_50_50'],
    typical_impact: '배송비 $10-25 범위',
    evaluate_hint: 'Shipping cost $10-25. Who pays is a common negotiation term.',
  },
  {
    id: 'warranty_period',
    parent_category: 'WARRANTY',
    display_name: '보증 기간',
    value_type: 'enum',
    value_range: ['none', '7_days', '14_days', '30_days'],
    typical_impact: '30일 보증 시 $10-20 프리미엄',
    evaluate_hint: 'Buyer-side warranty period. 30-day warranty adds $10-20 to perceived value.',
  },
  {
    id: 'return_policy',
    parent_category: 'WARRANTY',
    display_name: '반품 정책',
    value_type: 'enum',
    value_range: ['no_returns', 'defect_only', 'full_refund_7d'],
    typical_impact: '전액 환불 정책 시 $15-25 프리미엄',
    evaluate_hint: 'Full refund policy increases buyer confidence and justifies $15-25 premium.',
  },
  {
    id: 'imei_verification',
    parent_category: 'VERIFICATION',
    display_name: 'IMEI 인증',
    value_type: 'boolean',
    typical_impact: '미인증 시 거래 불가',
    evaluate_hint: 'IMEI must be verified clean (not blacklisted/stolen). Required for all transactions.',
  },
  {
    id: 'cosmetic_grade',
    parent_category: 'CONDITION',
    display_name: '외관 등급',
    value_type: 'enum',
    value_range: ['mint', 'excellent', 'good', 'fair', 'poor'],
    typical_impact: 'mint vs fair 차이 $50-100',
    evaluate_hint: 'Mint: like new. Excellent: minimal wear. Good: visible but minor. Fair: noticeable. Each grade ~$25-30 difference.',
  },
];
