/// <reference types="node" />
import { defineConfig } from "drizzle-kit";

export default defineConfig({
  dialect: "postgresql",
  // drizzle-kit loads TypeScript through CJS and cannot resolve this package's
  // ESM-style .js imports. `db:generate` builds first, then reads every compiled
  // table module explicitly. `verify:db-schema` keeps this list complete.
  schema: [
    "./dist/schema/addresses.js",
    "./dist/schema/admin-ops.js",
    "./dist/schema/advisor-messages.js",
    "./dist/schema/agent-levels.js",
    "./dist/schema/api-rate-limit.js",
    "./dist/schema/arp-segments.js",
    "./dist/schema/authentications.js",
    "./dist/schema/buddies.js",
    "./dist/schema/buddy-trades.js",
    "./dist/schema/buyer-interest-vectors.js",
    "./dist/schema/buyer-listings.js",
    "./dist/schema/category-check-learning.js",
    "./dist/schema/category-relatedness.js",
    "./dist/schema/chain-sync.js",
    "./dist/schema/commerce-orders.js",
    "./dist/schema/dispute-deposits.js",
    "./dist/schema/dispute-precedents.js",
    "./dist/schema/dispute-evidence-operations.js",
    "./dist/schema/dispute-evidence-scan-retry-alert-snapshots.js",
    "./dist/schema/disputes.js",
    "./dist/schema/ds-ratings.js",
    "./dist/schema/email-deliveries.js",
    "./dist/schema/hfmi-model-coefficients.js",
    "./dist/schema/hfmi-price-observations.js",
    "./dist/schema/intelligence-layer.js",
    "./dist/schema/listing-drafts.js",
    "./dist/schema/listing-embeddings.js",
    "./dist/schema/listings-published.js",
    "./dist/schema/negotiation-agents.js",
    "./dist/schema/negotiation-analytics.js",
    "./dist/schema/negotiation-moat.js",
    "./dist/schema/negotiation-sessions.js",
    "./dist/schema/notification-preferences.js",
    "./dist/schema/notifications.js",
    "./dist/schema/payment-test-operation-leases.js",
    "./dist/schema/payments.js",
    "./dist/schema/recommendation-logs.js",
    "./dist/schema/reviewer.js",
    "./dist/schema/seller-attestation-commits.js",
    "./dist/schema/settlement-releases.js",
    "./dist/schema/shipment-apv-invoice-documents.js",
    "./dist/schema/shipment-apv-invoice-reconciliation.js",
    "./dist/schema/shipment-apv-invoice-restoration-remediation.js",
    "./dist/schema/shipment-apv-invoice-restoration.js",
    "./dist/schema/shipments.js",
    "./dist/schema/skills.js",
    "./dist/schema/tag-graph.js",
    "./dist/schema/tag-idf-cache.js",
    "./dist/schema/tags.js",
    "./dist/schema/trust-ledger.js",
    "./dist/schema/trust-scores.js",
    "./dist/schema/user-wallets.js",
    "./dist/schema/waiting-intents.js",
    "./dist/schema/webhook-idempotency.js",
    "./dist/schema/websocket-auth-tickets.js",
  ],
  out: "./drizzle",
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
});
