// ─── Smart Contracts Package ─────────────────────────────────
// Post-MVP: Solidity smart contracts compiled with Foundry.
// This package will export ABIs, deployed addresses, and
// TypeScript bindings generated by viem/wagmi.

// TODO(post-mvp): Initialize Foundry project (forge init)
// TODO(post-mvp): Implement HaggleEscrow.sol on Base L2
// TODO(post-mvp): Export contract ABIs and addresses
// TODO(post-mvp): Integrate x402 USDC payment protocol

export interface ContractAddresses {
  escrow: `0x${string}` | null;
  // TODO(post-mvp): Add token contract address
}

/** Placeholder — no contracts deployed for MVP */
export const CONTRACT_ADDRESSES: ContractAddresses = {
  escrow: null,
};
